[2025-08-22T12:04:43.109+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_ml_pipeline.extract_crypto_data scheduled__2025-08-22T06:04:30.638336+00:00 [queued]>
[2025-08-22T12:04:43.112+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_ml_pipeline.extract_crypto_data scheduled__2025-08-22T06:04:30.638336+00:00 [queued]>
[2025-08-22T12:04:43.112+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-22T12:04:43.117+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_crypto_data> on 2025-08-22 06:04:30.638336+00:00
[2025-08-22T12:04:43.124+0000] {standard_task_runner.py:57} INFO - Started process 234 to run task
[2025-08-22T12:04:43.128+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_ml_pipeline', 'extract_crypto_data', 'scheduled__2025-08-22T06:04:30.638336+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/crypto_ml_pipeline.py', '--cfg-path', '/tmp/tmp56k83aol']
[2025-08-22T12:04:43.130+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask extract_crypto_data
[2025-08-22T12:04:43.181+0000] {task_command.py:416} INFO - Running <TaskInstance: crypto_ml_pipeline.extract_crypto_data scheduled__2025-08-22T06:04:30.638336+00:00 [running]> on host 619fd4ac9aad
[2025-08-22T12:04:43.220+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='crypto-mlops' AIRFLOW_CTX_DAG_ID='crypto_ml_pipeline' AIRFLOW_CTX_TASK_ID='extract_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T06:04:30.638336+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-22T06:04:30.638336+00:00'
[2025-08-22T12:04:43.221+0000] {logging_mixin.py:151} INFO - ðŸ”„ Extracting crypto data...
[2025-08-22T12:04:47.102+0000] {logging_mixin.py:151} INFO - âœ… Extracted 1000 records for BTC/USDT
[2025-08-22T12:04:47.446+0000] {logging_mixin.py:151} INFO - âœ… Extracted 1000 records for ETH/USDT
[2025-08-22T12:04:47.798+0000] {logging_mixin.py:151} INFO - âœ… Extracted 1000 records for BNB/USDT
[2025-08-22T12:04:48.141+0000] {logging_mixin.py:151} INFO - âœ… Extracted 1000 records for ADA/USDT
[2025-08-22T12:04:48.160+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 66, in extract_crypto_data
    minio_client.make_bucket(bucket_name)
  File "/home/airflow/.local/lib/python3.11/site-packages/minio/api.py", line 623, in make_bucket
    self._url_open(
  File "/home/airflow/.local/lib/python3.11/site-packages/minio/api.py", line 391, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /raw-data, request_id: 185E154460D4331A, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw-data
[2025-08-22T12:04:48.169+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_ml_pipeline, task_id=extract_crypto_data, execution_date=20250822T060430, start_date=20250822T120443, end_date=20250822T120448
[2025-08-22T12:04:48.176+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task extract_crypto_data (S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /raw-data, request_id: 185E154460D4331A, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw-data; 234)
[2025-08-22T12:04:48.190+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-22T12:04:48.201+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
